name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rails-version: '5.1'
            ruby-version: '2.5.1'
          - rails-version: '5.2'
            ruby-version: '2.5.1'
          - rails-version: '5.2'
            ruby-version: '2.6.2'
          - rails-version: '6.0'
            ruby-version: '2.5.1'
          - rails-version: '6.0'
            ruby-version: '2.6.2'
          - rails-version: '6.0'
            ruby-version: '2.7.1'
          - rails-version: '6.1'
            ruby-version: '2.5.1'
          - rails-version: '6.1'
            ruby-version: '2.6.2'
          - rails-version: '6.1'
            ruby-version: '2.7.1'
          - rails-version: '6.1'
            ruby-version: '3.0.1'
          - rails-version: '7.0'
            ruby-version: '2.7.1'
          - rails-version: '7.0'
            ruby-version: '3.0.1'
          - rails-version: '7.0'
            ruby-version: '3.1.0'
    name: Test against Ruby ${{ matrix.ruby-version }} / Rails ${{ matrix.rails-version }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails-version }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run rake tests
      run: bundle exec rake test
